version: '3.4'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: CourseSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batareyka
    ports:
      - "5432:5432"